apiVersion: v1
kind: Service
metadata:
  name: rmq-fork0
  namespace: ns-fork0
  labels:
    app: rmq-fork0
spec:
  selector:
    app: rmq-fork0
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
  type: NodePort
