apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/publicEndpoints: '[{"addresses":["172.16.96.156"],"port":32106,"protocol":"TCP","serviceName":"pms-uat:pms-workflow-web","allNodes":true},{"addresses":["172.16.96.156"],"port":32006,"protocol":"TCP","serviceName":"pms-uat:pms-workflow-web","allNodes":true},{"addresses":["172.16.96.156"],"port":80,"protocol":"HTTP","serviceName":"pms-uat:pms-workflow-web","ingressName":"pms-uat:pms-workflow-web-ingress","hostname":"pmsuat.vivo.xyz","path":"/workflow","allNodes":true}]'
  creationTimestamp: "2020-09-22T01:36:44Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: pms-workflow-web-uat
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pms-workflow-web
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: pms-workflow-web-0.2.0
  name: pms-workflow-web
  namespace: pms-uat
  resourceVersion: "51136777"
  selfLink: /apis/apps/v1/namespaces/pms-uat/deployments/pms-workflow-web
  uid: fdc656d2-5b27-4fc3-a058-9927a8c51a03
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: pms-workflow-web-uat
      app.kubernetes.io/name: pms-workflow-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-09-22T01:38:04Z"
        field.cattle.io/ports: '[[{"containerPort":8060,"dnsName":"pms-workflow-web","hostPort":0,"kind":"ClusterIP","name":"service-port","protocol":"TCP","sourcePort":0},{"containerPort":32006,"dnsName":"pms-workflow-web","hostPort":0,"kind":"ClusterIP","name":"dubbo-port","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pms-workflow-web-uat
        app.kubernetes.io/name: pms-workflow-web
    spec:
      containers:
      - env:
        - name: DUBBO_PORT_TO_BIND
          value: "32006"
        - name: DUBBO_PORT_TO_REGISTRY
          value: "32006"
        - name: JVM_OPTS
          value: -Xmx512M -Xms512M -XX:MaxMetaspaceSize=512M -XX:MetaspaceSize=512M
            -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:ErrorFile=/home/logs/gc/hs_err_pid%p.log
            -Xloggc:/home/logs/gc/gc.log -XX:HeapDumpPath=/home/logs/gc -XX:+PrintGCDetails
            -XX:+PrintGCDateStamps -verbose:class -XX:+HeapDumpOnOutOfMemoryError
            -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime
            -XX:+PrintHeapAtGC -Dapp.id=vivo-pms-calibration-file -Dapollo.meta=http://172.20.227.160:8080
            -Denv=uat -Duser.home=/usr/local/data/logs -DDUBBO_PORT_TO_REGISTRY=6613
            -DDUBBO_PORT_TO_BIND=6613 -Djava.security.egd=file:/dev/./urandom
        - name: DUBBO_IP_TO_REGISTRY
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: ZK_INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: it-registry.vivo.xyz/ipd/pms-workflow-web:uat-1.0.0
        imagePullPolicy: Always
        name: pms-workflow-web
        ports:
        - containerPort: 8060
          name: service-port
          protocol: TCP
        - containerPort: 32006
          name: dubbo-port
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /usr/local/data/logs
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pms-logs-uat
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-22T01:36:44Z"
    lastUpdateTime: "2020-09-22T01:36:44Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-09-22T02:37:38Z"
    lastUpdateTime: "2020-09-22T02:44:52Z"
    message: ReplicaSet "pms-workflow-web-797c45659c" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 3
  unavailableReplicas: 2
  updatedReplicas: 1
