apiVersion: apps/v1
kind: Deployment
metadata:
  name: v7-independent-ms
  namespace: ns-v7g16
  labels:
    k8s-app: v7-independent-ms
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      k8s-app: v7-independent-ms
  template:
    metadata:
      labels:
        k8s-app: v7-independent-ms
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: v7-independent-ms
        image: 10.190.2.171/v7/independent-ms:v2.0.284_v2.1.490_v2.0.264_v1.77.65_v2.4.23_v1.26.2_v5.1.13_v1.1.216_v1.0.21
        #image: 10.190.2.171/v7/independent-ms:v2.0.133_v2.1.67_v2.0.176_v1.71.39_v1.9.1_v1.20.9_v4.8.1_v1.1.102
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
             exec:
              command: ["/bin/bash", "-c", "PID=`ps -ef | grep java| grep -v grep | awk '{print $2}'` && kill -SIGTERM $PID && while ps -p $PID > /dev/null; do sleep 1; done;"]
        env:
        - name : configUrl
          value: mse-d7385ec0-zk.mse.aliyuncs.com:2181
        - name : JVM_OPTS
          value: "-server -XX:+UseContainerSupport -Xms5g -Xmx5g -XX:MaxMetaspaceSize=512M -XX:+DisableExplicitGC -XX:InitiatingHeapOccupancyPercent=70 -Duser.timezone=GMT+8 -Dfile.encoding=UTF-8 -XX:CompressedClassSpaceSize=128m -XX:NativeMemoryTracking=detail -javaagent:/jmx_prometheus_javaagent-0.15.0.jar=3010:/jmx_exporter.yml -javaagent:/usr/local/ppagent/pinpoint-bootstrap-2.0.4.jar -Dpinpoint.applicationName=ns-v7g16 -Dpinpoint.agentId=independentms"
        - name : clusterName
          value: ns-v7g16
        - name : sentinelDashboardServer
          value: "sentinel-dashboard:8888"
        - name: MALLOC_ARENA_MAX
          value: "4"
        resources:
          limits:
            cpu: 2000m
            memory: 7Gi
          requests:
            cpu: 500m
            memory: 6Gi
        ports:
        - name: web
          containerPort: 20880
        - name: health
          containerPort: 9998
        - name: jmx
          containerPort: 3010
        livenessProbe:
          httpGet:
            path: /monitor/healthDubbo
            port: health
          failureThreshold: 8
          initialDelaySeconds: 70
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /monitor/healthDubbo
            port: health
          failureThreshold: 6
          initialDelaySeconds: 35
          periodSeconds: 5
          timeoutSeconds: 2
      serviceAccountName: sa-v7g16
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: v7-independent-ms
  namespace: ns-v7g16
  labels:
    k8s-app: v7-independent-ms
    prometheus: jvm
spec:
  selector:
    k8s-app: v7-independent-ms
  ports:
  - name: web
    port: 20880
    targetPort: 20880
  - name: jmx
    port: 3010
    targetPort: 3010
