global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:25'
  smtp_from: '@qq.com'
  smtp_auth_username: '454576310@qq.com'
  smtp_auth_password: 'nqfjknltrqwvbjdg'
  smtp_require_tls: false
route:
  group_by: ['job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
receivers:
- name: 'default'
  email_configs:
  - to: '454576310@qq.com'
    send_resolved: true
