apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: kube-system
spec:
  endpoints:
  - path: /metrics
    port: prom
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: redis
