apiVersion: projectcalico.org/v3
kind: Node
metadata:
  annotations:
    projectcalico.org/kube-labels: '{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/arch":"amd64","kubernetes.io/hostname":"10.124.0.62","kubernetes.io/os":"linux","kubernetes.io/role":"master"}'
  creationTimestamp: null
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: 10.124.0.62
    kubernetes.io/os: linux
    kubernetes.io/role: master
    i-am-a-route-reflector: true
  name: dgvxl6775
spec:
  bgp:
    ipv4Address: 10.124.0.62/24
    ipv4IPIPTunnelAddr: 172.20.7.128
    # 设置集群ID
    routeReflectorClusterID: 224.0.0.1
  orchRefs:
  - nodeName: 10.124.0.62
    orchestrator: k8s
