---
- hosts: nodes
  remote_user: vivoauto
  become: yes
  gather_facts: false
  tasks:
  - name: test shell
    shell: id user1
    register: shell_status
  # - name: test debug
    # debug: var="shell_status.stdout"

