apiVersion: v1
kind: Service
metadata:
  name: bos-fileserver
  namespace: ns-v7g5
  labels:
    k8s-app: bos-fileserver
spec:
  selector:
    k8s-app: bos-fileserver
  ports:
  - port: 8101
    name: fileserver
    targetPort: 8101
  - port: 8765
    name: attachmentserver
    targetPort: 8765
  type: ExternalName
  externalName: bos-fileserver.ns-basesvc.svc.cluster.local
