apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-rabbitmq-exporter
  name: rabbitmq-exporter
  namespace: ns-v7g7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-rabbitmq-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-rabbitmq-exporter
    spec:
      containers:
      - env:
        - name: RABBIT_URL
          value: http://rmq-g7:15672
        - name: RABBIT_USER
          value: monitor
        - name: RABBIT_PASSWORD
          value: IU9xa3U8q#5A
        - name: PUBLISH_PORT
          value: "9419"
        - name: LOG_LEVEL
          value: info
        - name: RABBIT_CAPABILITIES
          value: bert,no_sort
        - name: INCLUDE_QUEUES
          value: .*
        - name: INCLUDE_VHOST
          value: .*
        - name: SKIP_QUEUES
          value: ^$
        - name: SKIPVERIFY
          value: "false"
        - name: SKIP_VHOST
          value: ^$
        - name: RABBIT_EXPORTERS
          value: exchange,node,overview,queue
        - name: OUTPUT_FORMAT
          value: TTY
        - name: RABBIT_TIMEOUT
          value: "30"
        - name: MAX_QUEUES
          value: "0"
        image: kbudde/rabbitmq-exporter:v0.29.0
        name: prometheus-rabbitmq-exporter        
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: publish
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 9419
          name: publish
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: publish
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-rabbitmq-exporter
  name: rabbitmq-exporter
  namespace: ns-v7g7
spec:
  ports:
  - name: rabbitmq-exporter
    port: 9419
    protocol: TCP
    targetPort: publish
  selector:
    app: prometheus-rabbitmq-exporter
  type: ClusterIP

