apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-rabbitmq.rules
  namespace: monitoring
spec:
  groups:
  - name: RabbitMQ
    rules:
    - alert: RabbitMQDown
      expr: rabbitmq_running == 0
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: RabbitMQ down.
        description: RabbitMQ node {{ $labels.node }} down for 30s.
    - alert: RabbitMQPartition
      expr: rabbitmq_partitions != 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: RabbitMQ partition.
        description: RabbitMQ cluster where RabbitMQ node {{ $labels.node }} in has split to {{ $value }} partitions.
    - alert: RabbitMQSocketsLow
      expr: rabbitmq_sockets_used / rabbitmq_sockets_total * 100 > 90
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: RabbitMQ available socket is low.
        description: Available socket of RabbitMQ node {{ $labels.node }} is low.
        value: "{{ $value }}"
    - alert: RabbitMQFdLow
      expr: rabbitmq_fd_used / rabbitmq_fd_total * 100 > 90
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: RabbitMQ available fd is low.
        description: Available fd of RabbitMQ node {{ $labels.node }} is low.
        value: "{{ $value }}"      
    - alert: RabbitMQNodeMemoryAlarm
      expr: rabbitmq_node_mem_alarm != 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: RabbitMQ node memory alarm.
        description: RabbitMQ node {{ $labels.node }} memory alarm.
        value: "{{ $value }}"      
    - alert: RabbitMQNodeDiskFreeAlarm
      expr: rabbitmq_node_disk_free_alarm != 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: RabbitMQ node disk free alarm.
        description: RabbitMQ node {{ $labels.node }} disk free alarm.
        value: "{{ $value }}"      
   
