apiVersion: v1
kind: Service
metadata:
  name: bos-fileserver-attach-v5-rsync-v7
  namespace: ns-basesvc
  labels:
    k8s-app: bos-fileserver-attach-v5-rsync-v7
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-id: lb-bp14sii6rqf6ryw901vt2
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
spec:
  selector:
    k8s-app: bos-fileserver
  ports:
  - port: 8765
    name: attachmentserver
    targetPort: 8765
  type: LoadBalancer
