kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-config-ls
  namespace: ns-basesvc
data:
  logstash.conf: |
   input {    
    kafka {
        bootstrap_servers => "10.190.2.191:9092,10.190.2.190:9092,10.190.2.192:9092"
        group_id => "logstash-ls"
        topics => "topic-jdyapp-log"       
        consumer_threads => 5
        decorate_events => false
        codec => json        
      }   
    }
   output {
    elasticsearch { 
     hosts => ["10.190.2.189:9200"]
     document_type => "applog"
     template_name => "app-biz-*"
     template_overwrite => true
     index => "app-biz-%{logtype}-%{+YYYY.MM.dd}"     
     codec => json
      }  
    } 
