apiVersion: v1
kind: ConfigMap
metadata:
  name: xlog-judge-conf
  namespace: ns-basesvc
  labels:
    name: xlog-judge-conf
data:
  application.yml: |
    database:
      type: postgresql
      url: jdbc:postgresql://pgm-bp1wqhoanej8w6lo146050.pg.rds.aliyuncs.com:1921/xlog?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&currentSchema=public
      username: monitor_user
      password: JIG2vjSpNF22Qp40
    kafka:
      url: 10.190.2.191:9092,10.190.2.190:9092,10.190.2.192:9092
      group_id: xlog-judge
    alert:
      dashboard:
        url: http://10.190.2.249:8080/api/alert
        token: qhQIez-9IMDO8OjLqQZIeNptE7w7rnaKDdxEoYhO
        environment: Production
        region: CH
      yzj: http://crp.kingdee.com/cd/sendMsgToYZJ?groupId={0}&content={1}
    spring:
      profiles:
        include: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xlog-judge
  namespace: ns-basesvc
  labels:
    k8s-app: xlog-judge
spec:
  selector:
    matchLabels:
      k8s-app: xlog-judge
  template:
    metadata:
      labels:
        k8s-app: xlog-judge
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: xlog-judge
        configMap:
          name: xlog-judge-conf
          items:
          - key: application.yml
            path: path/to/application.yml
      containers:
      - name: xlog-judge
        image: 10.190.2.171/xlog/xlog-judge:1.4.4
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: xlog-judge
          mountPath: /application.yml
          subPath: path/to/application.yml
        env:
        - name: JAVA_OPTIONS
          value: "-Xms1024M -Xmx1024M"
        resources:
          limits:
            cpu: 2000m
            memory: 1500Mi
          requests:
            cpu: 300m
            memory: 1000Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xlog-judge
  namespace: ns-basesvc
  labels:
    k8s-app: xlog-judge
spec:
  selector:
    k8s-app: xlog-judge
  ports:
    - port: 8080
