# apiVersion: batch/v1
# kind: Job
# metadata:
  # name: job-demo
# spec:
  # completions: 6
  # parallelism: 2
  # template:
    # metadata:
      # name: job-demo
    # spec:
      # restartPolicy: Never
      # # restartPolicy: OnFailure
      # containers:
      # - name: counter
        # image: busybox
        # command:
        # - "bin/sh"
        # - "-c"
        # - "for i in {1..20}; do echo $i; done"

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-demo
spec:
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: hello
            image: busybox
            args:
            - "bin/sh"
            - "-c"
            - "date; echo Hello from the Kubernetes cluster"
