# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: opspv
# spec:
  # capacity:
    # storage: 20Gi
  # accessModes:
  # - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  # nfs:
    # server: 10.151.30.57
    # path: /data/k8s

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
  # name: rbdpvc
# spec:
  # accessModes:
    # - ReadWriteOnce
    # # - ReadWriteMany/ReadOnlyMany
  # storageClassName: rbd
  # # volumeName: pvc-0146268f-f3bd-4f05-86e8-53069942236c #delete claimRef in pv
  # resources:
    # requests:
      # storage: 1Gi

# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jnlp
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany/ReadOnlyMany
  storageClassName: cephfs
  # volumeName: pvc-0146268f-f3bd-4f05-86e8-53069942236c #delete claimRef in pv
  resources:
    requests:
      storage: 10Gi
