# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: opspv
# spec:
  # capacity:
    # storage: 20Gi
  # accessModes:
  # - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  # nfs:
    # server: 10.151.30.57
    # path: /data/k8s

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-operator-grafana
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany/ReadOnlyMany
  # storageClassName: rbd
  volumeName: pvc-707b2ac0-7444-4744-b70e-b50113978086 #delete claimRef in pv
  resources:
    requests:
      storage: 10Gi

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
  # name: jnlp
# spec:
  # accessModes:
    # - ReadWriteOnce
    # # - ReadWriteMany/ReadOnlyMany
  # storageClassName: cephfs
  # resources:
    # requests:
      # storage: 10Gi
