apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tomcat
  template:
    metadata:
      labels:
        run: tomcat
    spec:
      containers:
      - image: tomcat:8-jre8-alpine
        # 可另外挂载空白卷追踪自定义日志文件
        volumeMounts:
         - mountPath: /usr/local/tomcat/logs
           name: tomcat-log
        name: tomcat
        env:
        - name: CONVEYOR_ENABLED
          value: "true"
        # 定义自定义日志路径
        - name: CONVEYOR_PATH
          value: "access-index:/usr/local/tomcat/logs/localhost_access_log.*.txt;stdout-index:stdout"
      # 声明空白卷
      volumes:
      - emptyDir: {}
        name: tomcat-log
