# apiVersion: v1
# kind: PersistentVolume
# metadata:
  # name: opspv
# spec:
  # capacity:
    # storage: 20Gi
  # accessModes:
  # - ReadWriteMany
  # persistentVolumeReclaimPolicy: Delete
  # nfs:
    # server: 10.151.30.57
    # path: /data/k8s

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
  # name: prometheus-operator-grafana
# spec:
  # accessModes:
    # - ReadWriteOnce
    # # - ReadWriteMany/ReadOnlyMany
  # # storageClassName: rbd
  # volumeName: pvc-707b2ac0-7444-4744-b70e-b50113978086 # 先删pvc: 删除对应pv中的claimRef属性, 然后重新创建pvc。
  # 先删pv: 删除pv中finalizers属性，然后重新部署pv。二者操作都要记得提前保存pv,pvc。
  # resources:
    # requests:
      # storage: 10Gi

# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvc
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany/ReadOnlyMany
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
