# apiVersion: v1
# kind: Pod
# metadata:
  # name: memory-demo
# spec:
  # containers:
  # - name: memory-demo
    # image: polinux/stress
    # resources:
      # requests:
        # memory: "50Mi"
      # limits:
        # memory: "300Mi"
    # command: ["stress"]
    # args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]

---

# apiVersion: v1
# kind: Pod
# metadata:
  # name: cpu-demo
# spec:
  # containers:
  # - name: cpu-demo
    # image: vish/stress
    # resources:
      # limits:
        # cpu: "1"
      # requests:
        # cpu: "0.5"
    # args:
    # - -cpus
    # - "2"

---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
  # name: mem-cpu-demo
  # namespace: testns
# spec:
  # hard:
    # requests.cpu: "1"
    # requests.memory: 1Gi
    # limits.cpu: "2"
    # limits.memory: 2Gi
    # pods: "3"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: testns
spec:
  limits:
  - default:  # default limit
      memory: 512Mi
      cpu: 1
    defaultRequest:  # default request
      memory: 256Mi
      cpu: 0.5
    max:  # max limit
      memory: 800Mi
      cpu: 2
    min:  # min request
      memory: 100Mi
      cpu: 0.3
    maxLimitRequestRatio:  # max value for limit / request
      memory: 2
      cpu: 2
    type: Container # limit type, support: Container / Pod / PersistentVolumeClaim
