apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxdemo
  template:
    metadata:
      labels:
        app: nginxdemo
    spec:
      containers:
      - name: nginxdemo
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: nginxdemo
spec:
  selector:
    app: nginxdemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginxdemo
spec:
  rules:
  - host: nginxdemo.k8s.maimaiti.site
    http:
      paths:
      - path: /
        backend:
          serviceName: nginxdemo
          servicePort: 80
