apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: v7-blue
  namespace: ns-v7g16
  labels:
    k8s-app: v7-blue
spec:
  selector:
    matchLabels:
      k8s-app: v7-blue
  template:
    metadata:
      labels:
        k8s-app: v7-blue
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
      - name: v7-blue
        image: 10.190.2.171/sinbad/blue:v1.0.4
        #image: 10.190.2.171/sinbad/blue:v1.0.2
        imagePullPolicy: IfNotPresent
        env:
        - name : ENV_MYSQL
          value: '{"blue":{"host":"rm-bp17cw7r459xfhb6j35910.mysql.rds.aliyuncs.com","port":"3306","usr":"sa","pwd":"GXJ8paKoA$YE","db":"blue"}}'
        - name : ENV_URL_LONG
          value: 'http://10.190.2.173:8086/api/v1/namespaces/ns-basesvc/endpoints/v7-long-wshttp'
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 2000Mi
        ports:
        - containerPort: 6789
      serviceAccountName: sa-v7g16
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: v7-blue
  namespace: ns-v7g16
  labels:
    k8s-app: v7-blue
spec:
  selector:
    k8s-app: v7-blue
  ports:
  - port: 6789
    targetPort: 6789
    name: blue
