apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-redis
  namespace: ns-v7g1
spec:
  template:
    metadata:
      labels:
        type: logstash-redis
    spec:
      hostAliases:
      - ip: "10.190.2.184"
        hostnames:
        - "v7log-redis.jdy.com"
      containers:
      - image: 10.190.2.171/base/logstash:redis
        name: logstash-redis
        command:
        - logstash
        - '-f'
        - '/etc/logstash/logstash.conf'
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 1500Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/logstash/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config-redis
            items:
              - key: logstash.conf
                path: logstash.conf
      serviceAccountName: sa-v7g1
      imagePullSecrets:
      - name: regsecret
