apiVersion: v1
data:
  logstash.conf: "input {\n  redis {\n      data_type => \"list\"\n      key => \"tf-ali-access\"\n
    \     host => \"log-redis\"\n  }\n }\ninput {\n  redis {\n      data_type => \"list\"\n
    \     key => \"tftmc-ali-access\"\n      host => \"log-redis\"\n  }\n }\ninput
    {\n  redis {\n      data_type => \"list\"\n      key => \"tf-long-access\"\n      host
    => \"log-redis\"\n  }\n }\nfilter {\n  if [url] =~ \".*\\.(html|htm|gif|jpg|jpeg|bmp|png|ico|txt|js|css|ttf)$\"
    {\n     drop { }\n }\n if \"/web/heartbeat\" in [url] {\n     drop {} \n }\n if
    \"/live.html\" in [url] { \n     drop {}\n }\n mutate {\n   gsub => [\"requestBody\",
    \"\\x22\", \"\"]\n   gsub => [\"message\", \":-,\", \":0,\"]\n }\n json{\n     source
    => \"message\"\n     remove_field => [\"beat\",\"message\"]\n }\n if \"-\" in
    [responseTime] {\n   mutate {\n     replace => {\n       \"responseTime\" => \"0\"\n
    \    }\n   }\n }\n ruby { \n    code => \"event.set('index_day', event.timestamp.time.localtime.strftime('%Y.%m.%d'))\"
    \n   }\n urldecode {\n  all_fields=>true\n  } \n }\n output {\n   elasticsearch
    {\n     hosts=> \"10.190.2.189:9200\"\n     index => \"logstash-%{type}-%{index_day}\"\n
    \    template_overwrite => true\n     template => \"/usr/local/success.json\"\n
    \ }\n } \n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"logstash.conf":"input {\n  redis {\n      data_type =\u003e \"list\"\n      key =\u003e \"tf-ali-access\"\n      host =\u003e \"log-redis\"\n  }\n }\ninput {\n  redis {\n      data_type =\u003e \"list\"\n      key =\u003e \"tftmc-ali-access\"\n      host =\u003e \"log-redis\"\n  }\n }\ninput {\n  redis {\n      data_type =\u003e \"list\"\n      key =\u003e \"tf-long-access\"\n      host =\u003e \"log-redis\"\n  }\n }\nfilter {\n  if [url] =~ \".*\\.(html|htm|gif|jpg|jpeg|bmp|png|ico|txt|js|css|ttf)$\" {\n     drop { }\n }\n if \"/web/heartbeat\" in [url] {\n     drop {} \n }\n if \"/live.html\" in [url] { \n     drop {}\n }\n mutate {\n   gsub =\u003e [\"requestBody\", \"\\x22\", \"\"]\n   gsub =\u003e [\"message\", \":-,\", \":0,\"]\n }\n json{\n     source =\u003e \"message\"\n     remove_field =\u003e [\"beat\",\"message\"]\n }\n if \"-\" in [responseTime] {\n   mutate {\n     replace =\u003e {\n       \"responseTime\" =\u003e \"0\"\n     }\n   }\n }\n ruby { \n    code =\u003e \"event.set('index_day', event.timestamp.time.localtime.strftime('%Y.%m.%d'))\" \n   }\n urldecode {\n  all_fields=\u003etrue\n  } \n }\n output {\n   elasticsearch {\n     hosts=\u003e \"10.190.2.189:9200\"\n     index =\u003e \"logstash-%{type}-%{index_day}\"\n     template_overwrite =\u003e true\n     template =\u003e \"/usr/local/success.json\"\n  }\n } \n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"logstash-config-redis","namespace":"ns-v7g1"}}
  creationTimestamp: 2019-09-24T03:36:04Z
  name: logstash-config-redis
  namespace: ns-v7g1
  resourceVersion: "341123279"
  selfLink: /api/v1/namespaces/ns-v7g1/configmaps/logstash-config-redis
  uid: 6fc7348a-de7c-11e9-9991-00163e0fd0a4
