apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: ns-v7g1
spec:
  template:
    metadata:
      labels:
        type: logstash
    spec:
      containers:
      - image: 10.190.2.171/base/logstash:7.3.0
        name: logstash
        command:
        - logstash
        - '-f'
        - '/etc/logstash/logstash.conf'
        resources:
          limits:
            cpu: 4000m
            memory: 5000Mi
          requests:
            cpu: 500m
            memory: 4000Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/logstash/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
      serviceAccountName: sa-v7g1
      imagePullSecrets:
      - name: regsecret
