apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pvc-protection
  name: isc-v7g11-inde
  namespace: ns-v7g11
spec:
  accessModes:
  - ReadWriteMany
  dataSource: null
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      alicloud-pvname: isc-v7g11-inde-pv
  storageClassName: nas
  volumeName: isc-v7g11-inde-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  phase: Bound
