apiVersion: v1
kind: Service
metadata:
  name: v7-g5-monitor
  namespace: ns-v7g8
  labels:
    k8s-app: v7-scm-bosv1
    prometheus: jvm
spec:
  selector:
    k8s-app: v7-scm-bosv1
  ports:
  - name: web 
    port: 20880
    targetPort: 20880
  - name: jmx
    port: 3010
    targetPort: 3010
