apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    com.kingdee.kcs.clusterenv: ""
#    com.kingdee.kcs.deploytime: "1585038433"
#    deployment.kubernetes.io/revision: "1"
#  creationTimestamp: "2020-03-24T08:27:14Z"
#  generation: 1
  labels:
   # cluster: clustername
    app: mservice-qing
  name: mservice-qing
  namespace: ns-v7yqy
#  resourceVersion: "139869"
#  selfLink: /apis/extensions/v1beta1/namespaces/clustername/deployments/mservice-qing
#  uid: 43b46b86-6da9-11ea-ab79-08002792b40b
spec:
#  progressDeadlineSeconds: 600
  replicas: 1
#  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mservice-qing
 #     cluster: clustername
 #     sname: mservice-qing
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
 #     annotations:
 #       com.kingdee.kcs.zid: "5"
 #     creationTimestamp: null
      labels:
        app: mservice-qing
 #       cluster: clustername
 #       sname: mservice-qing
    spec:
      serviceAccountName: sa-v7yqy
      containers:
      - env:
        - name: clusterName
          value: v7yqy001
        - name: configUrl
          value: 10.190.2.34:2181,10.190.2.37:2181,10.190.2.50:2181
        - name: appName
          value: mservice-qing
        - name: configAppName
          value: mservice
        - name: WEB_PORT
          value: "8080"
        - name: ENABLE_JETTY
          value: "true"
        - name: appSplit
          value: "false"
        - name: appIds
          value: qing
        - name: APPSTORE_URL
          value: http://10.190.2.50:8090/appstore/cosmic
        - name: JVM_OPTS
          value: -server -Xms4096m -Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+DisableExplicitGC
            -Duser.timezone=GMT+8 -Dfile.encoding=UTF-8 -XX:+PrintGCDateStamps -XX:+HeapDumpOnOutOfMemoryError
            -XX:HeapDumpPath=/data/QingStorage/ -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions
            -XX:MaxGCPauseMillis=100 -XX:InitiatingHeapOccupancyPercent=40 -XX:G1NewSizePercent=5
            -XX:G1MaxNewSizePercent=75 -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=5
            -XX:G1MixedGCCountTarget=5 -XX:G1LogLevel=finest -XX:+PrintGCDetails -XX:+PrintAdaptiveSizePolicy
            -XX:ParallelGCThreads=4 -XX:+UseStringDeduplication -XX:G1OldCSetRegionThresholdPercent=15
            -DSchedule.disableToWork=true -DJMX_HTTP_ADMIN_USER=admin -DJMX_HTTP_ADMIN_PASSWORD=admin
            -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
            -Xloggc:/data/QingStorage/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=15
            -XX:GCLogFileSize=5M
        - name: BIZLIBS
          value: bd-bd,biz-bos-ext
        - name: TRDLIBS
          value: trd.xml,trd-qing
        - name: BOSLIBS
          value: bos.xml,bos-qing
        - name: webmserviceinone
          value: "true"
        image: kcr.kingdee.com/support/v2.0/mservice:v-20191220
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        name: mservice-qing
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: v-015850384330
          readOnly: true
        - mountPath: /var/data/QingStorage
          name: qing-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
#      schedulerName: default-scheduler
#      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: v-015850384330
      - name: qing-data
        persistentVolumeClaim:
          claimName: cq-qing-pvc
      nodeSelector:
        cq: v7yqy 
