apiVersion: v1
kind: Config
clusters:
- name: "devops"
  cluster:
    server: "https://rancher.vivo.xyz/k8s/clusters/c-2qcgd"
- name: "devops-dgvxl5361"
  cluster:
    server: "https://172.16.159.91:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURReU5qQTNNVFkxT1ZvWERUTXdNRFF5TkRBM01UWTFPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5mU29mTmhXN1psCjUvbUlNZmRRaWNTQXBnME5lQllQNkFYaGk1eisxR2wybzd4SVVJMjNhc\
      jYwcHJ3UjVzYUJaOTcvY2VJR0JTNXUKVU12SUNGTEM4NjVhcFFIc25MWkNzNHh1MFppK0JOSjdLe\
      HlEbGhmQXZlVUUydmJUb2s5QnlZbWNOSFMyazR0NwpoNXRKNVNjZ1dLbFdkNENkMUhsSUNTUGdPU\
      HVvTW1FUFl0a2RucWdoRWRLeE43VFlweGJZWkJRbXhhd05oZ2NzCndhOXZURWh6RmtBdUhuMmY3L\
      3lqekJ3RXA4cllIcmVvS21ST3dzVTlwS01tWHMxWEV4QkFCMXU5OVdNQmRLVngKbGtyQ0xLcXRYT\
      zBzZllackwwT2lBc3BVTGxWYjkyYllLcWcyM3hQazRiWlFmM052bFk2SjZ0Z2JUM2FXOGRiawpkR\
      WxrendaVXo0a0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTkp5aFQ4RktSNUhjZUtJTHo2N3hue\
      EJVRktoWnJXZnczeisKVzU4K2M3OWkwTW11b0tiZTREcmY1ekQ1M3c2Z0hiNmZObWtKSm0xMDVQQ\
      25NTVU0YWxhYUlXZEtWMEQ1U2RJYgpDV2xTTTlsVVFkd1JYT0wwV3c4TmZJR1FMdDJQMEg1Wm9JV\
      U95OGxOMDdYOEZCWTVCWEdxUTJkNU5MOTBLVUNTCldUQXBWdm1aZmQvS2NRRFJyZjZ2U2RUbjZac\
      1NxNzhjWXlRaEJDVkk0cm55NVJhMWsxMXlTeXZIYmdjUnJJWHIKdC8yblhLODVFQzRuVC9UazRCL\
      3hrcUM2cjJ4bjFBbU5KOXZiTklYTDE5YzgyYnRMZ1Bhd2xHK0FzNUkvd0M4WQo5dmNrL3lSeTZlM\
      lFQU0c5bGdDTzJ0T2pqYkRvQzlFRE1PdVc4UXptQWZRK2xsYVZFTlU9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "devops-dgvxl5359"
  cluster:
    server: "https://172.16.159.89:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURReU5qQTNNVFkxT1ZvWERUTXdNRFF5TkRBM01UWTFPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5mU29mTmhXN1psCjUvbUlNZmRRaWNTQXBnME5lQllQNkFYaGk1eisxR2wybzd4SVVJMjNhc\
      jYwcHJ3UjVzYUJaOTcvY2VJR0JTNXUKVU12SUNGTEM4NjVhcFFIc25MWkNzNHh1MFppK0JOSjdLe\
      HlEbGhmQXZlVUUydmJUb2s5QnlZbWNOSFMyazR0NwpoNXRKNVNjZ1dLbFdkNENkMUhsSUNTUGdPU\
      HVvTW1FUFl0a2RucWdoRWRLeE43VFlweGJZWkJRbXhhd05oZ2NzCndhOXZURWh6RmtBdUhuMmY3L\
      3lqekJ3RXA4cllIcmVvS21ST3dzVTlwS01tWHMxWEV4QkFCMXU5OVdNQmRLVngKbGtyQ0xLcXRYT\
      zBzZllackwwT2lBc3BVTGxWYjkyYllLcWcyM3hQazRiWlFmM052bFk2SjZ0Z2JUM2FXOGRiawpkR\
      WxrendaVXo0a0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTkp5aFQ4RktSNUhjZUtJTHo2N3hue\
      EJVRktoWnJXZnczeisKVzU4K2M3OWkwTW11b0tiZTREcmY1ekQ1M3c2Z0hiNmZObWtKSm0xMDVQQ\
      25NTVU0YWxhYUlXZEtWMEQ1U2RJYgpDV2xTTTlsVVFkd1JYT0wwV3c4TmZJR1FMdDJQMEg1Wm9JV\
      U95OGxOMDdYOEZCWTVCWEdxUTJkNU5MOTBLVUNTCldUQXBWdm1aZmQvS2NRRFJyZjZ2U2RUbjZac\
      1NxNzhjWXlRaEJDVkk0cm55NVJhMWsxMXlTeXZIYmdjUnJJWHIKdC8yblhLODVFQzRuVC9UazRCL\
      3hrcUM2cjJ4bjFBbU5KOXZiTklYTDE5YzgyYnRMZ1Bhd2xHK0FzNUkvd0M4WQo5dmNrL3lSeTZlM\
      lFQU0c5bGdDTzJ0T2pqYkRvQzlFRE1PdVc4UXptQWZRK2xsYVZFTlU9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "devops-dgvxl5360"
  cluster:
    server: "https://172.16.159.90:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURReU5qQTNNVFkxT1ZvWERUTXdNRFF5TkRBM01UWTFPVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU5mU29mTmhXN1psCjUvbUlNZmRRaWNTQXBnME5lQllQNkFYaGk1eisxR2wybzd4SVVJMjNhc\
      jYwcHJ3UjVzYUJaOTcvY2VJR0JTNXUKVU12SUNGTEM4NjVhcFFIc25MWkNzNHh1MFppK0JOSjdLe\
      HlEbGhmQXZlVUUydmJUb2s5QnlZbWNOSFMyazR0NwpoNXRKNVNjZ1dLbFdkNENkMUhsSUNTUGdPU\
      HVvTW1FUFl0a2RucWdoRWRLeE43VFlweGJZWkJRbXhhd05oZ2NzCndhOXZURWh6RmtBdUhuMmY3L\
      3lqekJ3RXA4cllIcmVvS21ST3dzVTlwS01tWHMxWEV4QkFCMXU5OVdNQmRLVngKbGtyQ0xLcXRYT\
      zBzZllackwwT2lBc3BVTGxWYjkyYllLcWcyM3hQazRiWlFmM052bFk2SjZ0Z2JUM2FXOGRiawpkR\
      WxrendaVXo0a0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTkp5aFQ4RktSNUhjZUtJTHo2N3hue\
      EJVRktoWnJXZnczeisKVzU4K2M3OWkwTW11b0tiZTREcmY1ekQ1M3c2Z0hiNmZObWtKSm0xMDVQQ\
      25NTVU0YWxhYUlXZEtWMEQ1U2RJYgpDV2xTTTlsVVFkd1JYT0wwV3c4TmZJR1FMdDJQMEg1Wm9JV\
      U95OGxOMDdYOEZCWTVCWEdxUTJkNU5MOTBLVUNTCldUQXBWdm1aZmQvS2NRRFJyZjZ2U2RUbjZac\
      1NxNzhjWXlRaEJDVkk0cm55NVJhMWsxMXlTeXZIYmdjUnJJWHIKdC8yblhLODVFQzRuVC9UazRCL\
      3hrcUM2cjJ4bjFBbU5KOXZiTklYTDE5YzgyYnRMZ1Bhd2xHK0FzNUkvd0M4WQo5dmNrL3lSeTZlM\
      lFQU0c5bGdDTzJ0T2pqYkRvQzlFRE1PdVc4UXptQWZRK2xsYVZFTlU9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "devops"
  user:
    token: "kubeconfig-user-4cdkl.c-2qcgd:5wnqshp9b8b4k45hrmjbhrxkbjjsk9nsrkl42h42dl7dqss44x55hw"

contexts:
- name: "devops"
  context:
    user: "devops"
    cluster: "devops"
- name: "devops-dgvxl5361"
  context:
    user: "devops"
    cluster: "devops-dgvxl5361"
- name: "devops-dgvxl5359"
  context:
    user: "devops"
    cluster: "devops-dgvxl5359"
- name: "devops-dgvxl5360"
  context:
    user: "devops"
    cluster: "devops-dgvxl5360"

current-context: "devops"

