apiVersion: v1
kind: Config
clusters:
- name: "it-k8s-uat"
  cluster:
    server: "https://rancherqa.vivo.xyz/k8s/clusters/c-jbc4r"
- name: "it-k8s-uat-dgvxl8610"
  cluster:
    server: "https://172.16.100.61:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURVeU5qQXhNREl6TTFvWERUTXdNRFV5TkRBeE1ESXpNMW93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1IWUlkbWh3SEFQCmErQ1dCaktSWHlHTmsraWpqSmdDdG1wd1hvU1ozbFhDbHhLcHEyMXJiK\
      1pUWWpoai9zR2dVeWU3cFIxbFVoVVAKS3pIU1NWdE4rbzJzTnV2TnRaL1oxeUtPcGtxUlNieUlkL\
      0t5UU9GMmtYUlFIbm5HMzkxL0V1ZUFUM0ZQUWIzLwpuRlNhT3dSdTlpMGNXWUpuTGhYVnQva2RJN\
      GRmUUdyK0NrV25BR0lrejZGRUp5bmNxcE96QjJLU3ExVUQ3dkYxCkdybEMxcXVtSWdEYnVyWXYzb\
      GF0REhvcEFQWWVWMHJKQmtnZ0g5YnNxRmYyRDFXWU5uSk9Va3Y1bC8wMGM2bkIKVENlR2NSb2Exc\
      VRmMEpVNmgwUzNCV282ZTFJbHR3K0kxSjJyK3hZdFJtd3ZmMVp5WHlaLzFZZW1WT2M3ZHRTYgo2b\
      GdtdUp0cFJIa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1IzNUo2UHdyQXBtRURMdUtnQVFid\
      jRSTlFwZmZaU2x2dngKb0F1STdKKzZvb3MrUVFaUTVQbm9OZllZZkxBNnY5MlBVd1kwWVoyTlZZY\
      2lVbTZod3Y1V3I4RjhLSUF5eStyZQpIYTJsVEVDYkRyTnVjc25xRGlieVN3RTI0dVZ2emxSUHp3b\
      XJ5VnhKSlJSNDRhcWVLYmh5a3BaS0JObGhhc0ViCm9UT2dac29ZYXR2bUlrMTdEVnRBSGJLeUllN\
      U1GUGgvd2dCbDBnQ3MwVWlUVEF1SVQ5RC94MTJicGNRdXh0USsKeVhMYk15V1ZvaVZLY1RpOXJIW\
      kpKVE9vMXBlaFU4NkhEL2tjbTVkR0J4VDB5UWZaSjhuWDFMSkRnMkRWOFA3agpUbTZaSHdKRmdrY\
      1VIMThIR3lQeCszK3djV25ScitCNmxTV2RXQkhORXlwczJGbzc1L2M9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "it-k8s-uat-dgvxl8612"
  cluster:
    server: "https://172.16.100.60:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURVeU5qQXhNREl6TTFvWERUTXdNRFV5TkRBeE1ESXpNMW93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1IWUlkbWh3SEFQCmErQ1dCaktSWHlHTmsraWpqSmdDdG1wd1hvU1ozbFhDbHhLcHEyMXJiK\
      1pUWWpoai9zR2dVeWU3cFIxbFVoVVAKS3pIU1NWdE4rbzJzTnV2TnRaL1oxeUtPcGtxUlNieUlkL\
      0t5UU9GMmtYUlFIbm5HMzkxL0V1ZUFUM0ZQUWIzLwpuRlNhT3dSdTlpMGNXWUpuTGhYVnQva2RJN\
      GRmUUdyK0NrV25BR0lrejZGRUp5bmNxcE96QjJLU3ExVUQ3dkYxCkdybEMxcXVtSWdEYnVyWXYzb\
      GF0REhvcEFQWWVWMHJKQmtnZ0g5YnNxRmYyRDFXWU5uSk9Va3Y1bC8wMGM2bkIKVENlR2NSb2Exc\
      VRmMEpVNmgwUzNCV282ZTFJbHR3K0kxSjJyK3hZdFJtd3ZmMVp5WHlaLzFZZW1WT2M3ZHRTYgo2b\
      GdtdUp0cFJIa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1IzNUo2UHdyQXBtRURMdUtnQVFid\
      jRSTlFwZmZaU2x2dngKb0F1STdKKzZvb3MrUVFaUTVQbm9OZllZZkxBNnY5MlBVd1kwWVoyTlZZY\
      2lVbTZod3Y1V3I4RjhLSUF5eStyZQpIYTJsVEVDYkRyTnVjc25xRGlieVN3RTI0dVZ2emxSUHp3b\
      XJ5VnhKSlJSNDRhcWVLYmh5a3BaS0JObGhhc0ViCm9UT2dac29ZYXR2bUlrMTdEVnRBSGJLeUllN\
      U1GUGgvd2dCbDBnQ3MwVWlUVEF1SVQ5RC94MTJicGNRdXh0USsKeVhMYk15V1ZvaVZLY1RpOXJIW\
      kpKVE9vMXBlaFU4NkhEL2tjbTVkR0J4VDB5UWZaSjhuWDFMSkRnMkRWOFA3agpUbTZaSHdKRmdrY\
      1VIMThIR3lQeCszK3djV25ScitCNmxTV2RXQkhORXlwczJGbzc1L2M9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"
- name: "it-k8s-uat-dgvxl8611"
  cluster:
    server: "https://172.16.100.59:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN3akNDQ\
      WFxZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl3TURVeU5qQXhNREl6TTFvWERUTXdNRFV5TkRBeE1ESXpNMW93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQU1IWUlkbWh3SEFQCmErQ1dCaktSWHlHTmsraWpqSmdDdG1wd1hvU1ozbFhDbHhLcHEyMXJiK\
      1pUWWpoai9zR2dVeWU3cFIxbFVoVVAKS3pIU1NWdE4rbzJzTnV2TnRaL1oxeUtPcGtxUlNieUlkL\
      0t5UU9GMmtYUlFIbm5HMzkxL0V1ZUFUM0ZQUWIzLwpuRlNhT3dSdTlpMGNXWUpuTGhYVnQva2RJN\
      GRmUUdyK0NrV25BR0lrejZGRUp5bmNxcE96QjJLU3ExVUQ3dkYxCkdybEMxcXVtSWdEYnVyWXYzb\
      GF0REhvcEFQWWVWMHJKQmtnZ0g5YnNxRmYyRDFXWU5uSk9Va3Y1bC8wMGM2bkIKVENlR2NSb2Exc\
      VRmMEpVNmgwUzNCV282ZTFJbHR3K0kxSjJyK3hZdFJtd3ZmMVp5WHlaLzFZZW1WT2M3ZHRTYgo2b\
      GdtdUp0cFJIa0NBd0VBQWFNak1DRXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQ1IzNUo2UHdyQXBtRURMdUtnQVFid\
      jRSTlFwZmZaU2x2dngKb0F1STdKKzZvb3MrUVFaUTVQbm9OZllZZkxBNnY5MlBVd1kwWVoyTlZZY\
      2lVbTZod3Y1V3I4RjhLSUF5eStyZQpIYTJsVEVDYkRyTnVjc25xRGlieVN3RTI0dVZ2emxSUHp3b\
      XJ5VnhKSlJSNDRhcWVLYmh5a3BaS0JObGhhc0ViCm9UT2dac29ZYXR2bUlrMTdEVnRBSGJLeUllN\
      U1GUGgvd2dCbDBnQ3MwVWlUVEF1SVQ5RC94MTJicGNRdXh0USsKeVhMYk15V1ZvaVZLY1RpOXJIW\
      kpKVE9vMXBlaFU4NkhEL2tjbTVkR0J4VDB5UWZaSjhuWDFMSkRnMkRWOFA3agpUbTZaSHdKRmdrY\
      1VIMThIR3lQeCszK3djV25ScitCNmxTV2RXQkhORXlwczJGbzc1L2M9Ci0tLS0tRU5EIENFUlRJR\
      klDQVRFLS0tLS0K"

users:
- name: "it-k8s-uat"
  user:
    token: "kubeconfig-u-ql52d.c-jbc4r:ftdn8x999wf4f9rhwqbcx5bzjv8hgjw7cwcgbg4bmg7mc4njcqvpjq"

contexts:
- name: "it-k8s-uat"
  context:
    user: "it-k8s-uat"
    cluster: "it-k8s-uat"
- name: "it-k8s-uat-dgvxl8610"
  context:
    user: "it-k8s-uat"
    cluster: "it-k8s-uat-dgvxl8610"
- name: "it-k8s-uat-dgvxl8612"
  context:
    user: "it-k8s-uat"
    cluster: "it-k8s-uat-dgvxl8612"
- name: "it-k8s-uat-dgvxl8611"
  context:
    user: "it-k8s-uat"
    cluster: "it-k8s-uat-dgvxl8611"

current-context: "it-k8s-uat"

