apiVersion: v1
kind: Config
clusters:
- name: "rancher-fty"
  cluster:
    server: "https://rancher-fty.vivo.xyz/k8s/clusters/local"

users:
- name: "rancher-fty"
  user:
    token: "kubeconfig-user-d6zl4:9tmwl4xbff2sxjj8qplmrd6wptxnd9p86bsxbbsv95t8pfbbmbxl7d"

contexts:
- name: "rancher-fty"
  context:
    user: "rancher-fty"
    cluster: "rancher-fty"

current-context: "rancher-fty"

