apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-memory-limit-request-95.rules
  namespace: monitoring
spec:
  groups:
  - name: container-memory-limit-request-95.rules
    rules:
    - alert: PodWillOom
      annotations:
        description: '{{ $labels.name }} Pod memory used too much ,maybe will oom ,(current values is: {{ $value }} )'
      expr: floor(sum(container_memory_working_set_bytes{pod_name!~"(.*)prometheus(.*)"}) by (pod_name,namespace) / sum(label_join(kube_pod_container_resource_limits_memory_bytes,"pod_name", "", "pod")) by (pod_name,namespace)  / 2 * 100) > 98
      for: 60m
      lables:
        severity: warning
