apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-node-memory-limit-80.rules
  namespace: monitoring
spec:
  groups:
  - name: node-memory-limit-request-80.rules
    rules:
    - alert: NodeMemUsageAlert
      annotations:
        description: '{{ $labels.instance }} MEM usage above 90% (current value: {{ $value}})'
      expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) * 100 / node_memory_MemTotal_bytes >90
      for: 5m
      lables:
        severity: warning
