apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-disk-limit-request-10g.rules
  namespace: monitoring
spec:
  groups:
  - name: container-disk-limit-request-10G.rules
    rules:
    - alert: PodDiskUsageAlert
      annotations:
        summary: "namespace: {{$labels.namespace}}, pod_name: {{$labels.pod_name}} "
        description: 'Pod disk usage too much ,maybe will Evicted ,(current values is: {{ $value }}G )'
      expr: ceil( container_fs_usage_bytes{endpoint="http-metrics",id!="/",job="kubelet"} /1024 /1024 /1024 ) >29
      for: 5m
      lables:
        severity: warning
