apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-pod-cpu-used-alert5m.rules
  namespace: monitoring
spec:
  groups:
  - name: PodCpuUsed-alert5m.rules
    rules:
    - alert: PodCpuUsed-alert5m
      annotations:
        #summary: 'Pod: {{ $labels.container }} restart'
        description: 'namespace: {{ $labels.namespace }}, pod: {{ $labels.pod }} cpu used alert {{ $value }}, will kill this pod'
      expr: namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="v7-scm-bosv1"} * 1000 > 2700
      for: 2m
      lables:
        severity: warning
