apiVersion: apps/v1
kind: Deployment
metadata:
  name: v7-isc-bosv1
  namespace: ns-v7u1
  labels:
    k8s-app: v7-isc-bosv1
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      k8s-app: v7-isc-bosv1
  template:
    metadata:
      labels:
        k8s-app: v7-isc-bosv1
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      hostAliases:
      - ip: "10.190.2.240"
        hostnames:
        - "ppcol.jdy.com"
      containers:
      - name: v7-isc-bosv1
        image: 10.190.2.171/v7/isc:v2.0.244_v2.1.392_v1.0.6
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
             exec:
              command: ["/bin/bash", "-c", "PID=`ps -ef | grep java| grep -v grep | awk '{print $2}'` && kill -SIGTERM $PID && while ps -p $PID > /dev/null; do sleep 1; done;"]
        env:
        - name : configUrl
          value: mse-d7385ec0-zk.mse.aliyuncs.com:2181
        - name : JVM_OPTS
          value: "-server -Xms2g -Xmx2g -XX:MaxMetaspaceSize=512m -XX:+DisableExplicitGC -Duser.timezone=GMT+8 -Dfile.encoding=UTF-8 -XX:CompressedClassSpaceSize=128m -javaagent:/jmx_prometheus_javaagent-0.15.0.jar=3010:/jmx_exporter.yml -javaagent:/usr/local/ppagent/pinpoint-bootstrap-2.0.4.jar -Dpinpoint.applicationName=ns-v7u1 -Dpinpoint.agentId=isc"
        - name : clusterName
          value: ns-v7u1
        - name : sentinelDashboardServer
          value: "sentinel-dashboard:8888"
        - name: MALLOC_ARENA_MAX
          value: "4"
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 3Gi
        ports:
        - name: web 
          containerPort: 20880
        - name: jmx 
          containerPort: 3010
        readinessProbe:
          tcpSocket:
            port: 20880
          initialDelaySeconds: 70
          periodSeconds: 3
          failureThreshold: 6
          timeoutSeconds: 2
        volumeMounts:
          - name: isc-v7u1
            mountPath:  /datafile
      volumes:
        - name: isc-v7u1
          persistentVolumeClaim:
            claimName: isc-v7u1
      imagePullSecrets:
      - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: v7-isc-bosv1
  namespace: ns-v7u1
  labels:
    k8s-app: v7-isc-bosv1
    prometheus: jvm
spec:
  selector:
    k8s-app: v7-isc-bosv1
  ports:
  - name: web
    port: 20880
    targetPort: 20880
  - name: jmx
    port: 3010
    targetPort: 3010
