apiVersion: v1
kind: Service
metadata:
#  creationTimestamp: "2020-03-24T07:57:02Z"
  labels:
    app: mc
    name: mc
  name: mc
  namespace: ns-v7yqy
 # resourceVersion: "136825"
 # selfLink: /api/v1/namespaces/clustername/services/mc
 # uid: 0c2fe87d-6da5-11ea-ab79-08002792b40b
spec:
 # clusterIP: 10.24.243.78
#  externalTrafficPolicy: Cluster
  ports:
  - name: kcs-service-0
    nodePort: 30001
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mc
   # cluster: ns-v7yqy
    sname: mc
  sessionAffinity: None
  type: NodePort
#status:
#  loadBalancer: {}
