apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-rmq-g9
mountOptions:
- nolock,tcp,noresvport
- vers=3
parameters:
  driver: flexvolume
  server: "00d4b9dd-5hvc.cn-hangzhou.extreme.nas.aliyuncs.com:/share/ns-v7g9/rabbitmq"
provisioner: alicloud/nas
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rmq-g9
  namespace: ns-v7g9
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: sc-rmq-g9
