apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.kingdee.kcs.clusterenv: ""
    com.kingdee.kcs.deploytime: "1585037139"
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-03-24T07:57:02Z"
  generation: 2
  labels:
    cluster: clustername
  name: mc
  namespace: clustername
  resourceVersion: "137805"
  selfLink: /apis/extensions/v1beta1/namespaces/clustername/deployments/mc
  uid: 0c26c487-6da5-11ea-ab79-08002792b40b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mc
      cluster: clustername
      sname: mc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        com.kingdee.kcs.zid: "5"
      creationTimestamp: "2020-03-24T08:05:39Z"
      labels:
        app: mc
        cluster: clustername
        sname: mc
    spec:
      containers:
      - env:
        - name: clusterName
          value: mc
        - name: configUrl
          value: zkconfig
        - name: appName
          value: mc
        - name: configAppName
          value: mservice
        - name: WEB_PORT
          value: "8080"
        - name: ENABLE_JETTY
          value: "true"
        - name: appSplit
          value: "false"
        - name: APPSTORE_URL
          value: http://nginx_vip:8090/appstore/mc
        - name: JVM_OPTS
          value: -server -Xms3072m -Xmx3072m -XX:MaxMetaspaceSize=256m -XX:NativeMemoryTracking=summary
            -Duser.timezone=GMT+8 -Dfile.encoding=UTF-8 -Dxdb.enable=false -XX:+HeapDumpOnOutOfMemoryError
            -XX:HeapDumpPath=../logs/ -XX:+PrintGCApplicationStoppedTime
            -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+PrintAdaptiveSizePolicy -XX:+PrintGCDetails
            -XX:+PrintGCDateStamps -Xloggc:../logs/gc.%t.log -DdataCenterName=mc
        - name: webmserviceinone
          value: "true"
        - name: isMC
          value: "true"
        - name: is_unzip_dm_before_upgrade
          value: "false"
        - name: domain_contextUrl
          value: http://nginx_vip:8090/mc
        - name: lightweightdeploy
          value: "false"
        image: kcr.kingdee.com/support/v2.0/mservice:v-20191220
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        name: mc
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "2"
            memory: 5Gi
          requests:
            cpu: 200m
            memory: 5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: v-015850371390
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: v-015850371390
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-24T08:06:55Z"
    lastUpdateTime: "2020-03-24T08:06:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-24T07:57:02Z"
    lastUpdateTime: "2020-03-24T08:06:55Z"
    message: ReplicaSet "mc-6d6fbb947" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
