apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-pod-restart.rules
  namespace: monitoring
spec:
  groups:
  - name: pod-restart.rules
    rules:
    - alert: PodRestart
      annotations:
        #summary: 'Pod: {{ $labels.container }} restart'
        description: 'namespace: {{ $labels.namespace }}, pod: {{ $labels.pod }} restart {{ $value }} times'
      expr: changes(kube_pod_container_status_restarts_total[2m])>0
      #for: 1m
      lables:
        severity: warning
