apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: ack-prometheus-operator
    chart: ack-prometheus-operator-5.7.0
    heritage: Tiller
    release: ack-prometheus-operator
  name: ack-prometheus-operator-traefik-504.rules
  namespace: monitoring
spec:
  groups:
  - name: traefik-504.rules
    rules:
    - alert: StatusCode-504-TooHigh
      annotations:
        description: '{{ $labels.namespace }} / {{ $labels.code }} traefik 504 status code  above 10 in 1min ,(current values is: {{ $value }} )'
      expr: increase(traefik_entrypoint_requests_total{namespace="ns-v7g2",code="504"}[1m]) > 1
      for: 1m
      lables:
        severity: warning
