# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ns-v7g9
  labels:
    name: v7g9
---
# service account 
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: v7g9
  name: sa-v7g9
  namespace: ns-v7g9
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cr-v7g9
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
        - events
    verbs:
        - create
        - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: role-v7g9
  namespace: ns-v7g9
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
      - "ingress-controller-leader-nginx"
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rb-v7g9
  namespace: ns-v7g9
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-v7g9
subjects:
  - kind: ServiceAccount
    name: sa-v7g9
    namespace: ns-v7g9
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-v7g9
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-v7g9
subjects:
  - kind: ServiceAccount
    name: sa-v7g9
    namespace: ns-v7g9
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlHM1RDQ0JjV2dBd0lCQWdJUUJQeGczSUVjcjFlMmpNcVEwcEFpcFRBTkJna3Foa2lHOXcwQkFRc0ZBREJmDQpNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ2hNTVJHbG5hVU5sY25RZ1NXNWpNUmt3RndZRFZRUUxFeEIzDQpkM2N1WkdsbmFXTmxjblF1WTI5dE1SNHdIQVlEVlFRREV4VkhaVzlVY25WemRDQkRUaUJTVTBFZ1EwRWdSekV3DQpIaGNOTWpBd05qQTVNREF3TURBd1doY05Nakl3T0RBM01USXdNREF3V2pDQm1ERUxNQWtHQTFVRUJoTUNRMDR4DQpFakFRQmdOVkJBZ01DZVc1ditTNG5PZWNnVEVTTUJBR0ExVUVCd3dKNXJleDVaeXo1YmlDTVRrd053WURWUVFLDQpERERtdDdIbG5MUGx1SUxwaDVIb25iYm5zcjdtbHBma3VwSG52WkhudTV6bnA1SG1pb0RtbklucG1aRGxoYXpsDQpqN2d4RWpBUUJnTlZCQXNNQ2VhS2dPYWNyK21EcURFU01CQUdBMVVFQXd3SktpNXFaSGt1WTI5dE1JSUJJakFODQpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3Z25HQzhDMjlWY0cyOXlWM1VuZys1dVZ0T3FDDQowanV1SEFIWFNGdkRwQVQxanlKd0h2Rk01dERuTzNmTlJsZEVBNmZGT3JGQzhyUkErbXVTdlRiaHBNbTlrQ01IDQo0OHJQby9hMVFNY0J6Yk5uNmVJQXZtL3FDUGUvS2xuZ1JVSCt3eTgvcjgwU0hNZFBZdmx5bXdUNTZDTUxDK0J2DQpjWGJKT1EvcldPTzVjNkxob2lvL1V0R1E1UDM4Y0hLVUwwZ2U3Sit1NUxMT0xza3NKS0xJdFl1RjkwajZNRDloDQpXd1lPL0hhR0c3R08xTnNmaHBnd1NmU2I0RkhIeWRDWk9ZQnFTLzl1UndaMW1JbDNETmxMZk1QamVtZ1lpM3FoDQpvVGRTcmQ2QmdRbFdYeFhMQnFpUU0rUDBzQ3FHK3hqWVl0c0dqWnBTU24wTGh6R3pGaEIrUTFHTkN3SURBUUFCDQpvNElEV1RDQ0ExVXdId1lEVlIwakJCZ3dGb0FVa1o5ZU1SV3VFSit0WU1IM3djeXFTRFF2RENZd0hRWURWUjBPDQpCQllFRk4wNzNhODFWUzlyRkxQaEQ2aWp5QU1YZ0ptNE1CMEdBMVVkRVFRV01CU0NDU291YW1SNUxtTnZiWUlIDQphbVI1TG1OdmJUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHDQpBUVVGQndNQ01IVUdBMVVkSHdSdU1Hd3dOS0F5b0RDR0xtaDBkSEE2THk5amNtd3pMbVJwWjJsalpYSjBMbU52DQpiUzlIWlc5VWNuVnpkRU5PVWxOQlEwRkhNUzVqY213d05LQXlvRENHTG1oMGRIQTZMeTlqY213MExtUnBaMmxqDQpaWEowTG1OdmJTOUhaVzlVY25WemRFTk9VbE5CUTBGSE1TNWpjbXd3VEFZRFZSMGdCRVV3UXpBM0JnbGdoa2dCDQpodjFzQVFFd0tqQW9CZ2dyQmdFRkJRY0NBUlljYUhSMGNITTZMeTkzZDNjdVpHbG5hV05sY25RdVkyOXRMME5RDQpVekFJQmdabmdRd0JBZ0l3YndZSUt3WUJCUVVIQVFFRVl6QmhNQ0VHQ0NzR0FRVUZCekFCaGhWb2RIUndPaTh2DQpiMk56Y0M1a1kyOWpjM0F1WTI0d1BBWUlLd1lCQlFVSE1BS0dNR2gwZEhBNkx5OWpjbXd1WkdsbmFXTmxjblF0DQpZMjR1WTI5dEwwZGxiMVJ5ZFhOMFEwNVNVMEZEUVVjeExtTnlkREFNQmdOVkhSTUJBZjhFQWpBQU1JSUJmd1lLDQpLd1lCQkFIV2VRSUVBZ1NDQVc4RWdnRnJBV2tBZGdBcGViN3duams1SWZCV2M1OWpwWGZsdmxkOW5HQUsrUGxODQpYU1pjSlYzSGhBQUFBWEtZSGsyRUFBQUVBd0JITUVVQ0lCT3hNOXFlVmFGTllqM0lCUkJreEczNW9CcWozOWtXDQp4eS95U0JCdGlDclNBaUVBaTBjSDJHQUE3a1haTmZxazZLMktWUUcxUm9kYTB3dnB1dFp3TVBNUXdmUUFkZ0JSDQpvN0QxL1FGNW5GWnR1RGQ0and5a2Vzd2JKOHYzbm9oQ21nMysxSXNGNVFBQUFYS1lIazN6QUFBRUF3QkhNRVVDDQpJUUNMSk05OHF2cGdvaVFQbTZmVDFFazc3ZHhjL0pleHdyaDNuUStzRGVYZG1nSWdUak9kdWxtRlFvNHVoSnFhDQpUcXVEdmlGMUtoazgxajFtNENEN2d6by9hM0VBZHdCQnlNcXgzeUpHU2hER29Ub0pRb2RlVGpHTEd3UHI2MHZIDQphUENRWXBZRzlnQUFBWEtZSGsxRUFBQUVBd0JJTUVZQ0lRRFhqdVJsaklJemRzQkhaU1FXTlQ1bzVjU2pmdC96DQpOVGY4ZjA3STkyaXkxd0loQU1JQkFkMDE4N2dqS1BXMzNFaWpXNzNXRkJsalVoTjJGNjZpK3lVWVJKdk5NQTBHDQpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkFoS1pjUFkxbmM4UWxEUlNCQmJTaEZKQmdqaVgrRlBxdktmZzQwalFVDQpkQUlWWTRjUGF5bEVKb0RKTHJNVXlRaGRtdmJsT2NwRVBUQm1GUG4xdVdzbDJDY3hKS1h1Q1BYTlIwRnZsWm45DQpQNS9PT1JiUXNtQkxlS2E5MnZJNzhYY2xnQ2ViU0hiU3RjQmtGMXNnZWNaNW9zTDRZUGkwYmd2ejN2NzduWHFiDQozaUZXZ1hNVkdqZmFvUHZRbVV0VVBrenFNR0t4YmV1c2pJN3ZyemRFWmxDSXk0QkxMeDF2QlVBbTFsK0pMTFdKDQpDMHhmS0FtbUNBbjZKVjJaTk9qMW5QN0lrODJxTjRRUjB6MFZXSjM0MVVGSHcrdzZacCtKc1lSbUhGR0xjZ2QvDQpIUUMxNCsvZlNPSVloVkE3bHVGNnBwQjAwZUFqd2xsckwvem8xUjNtaGFaag0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGR2pDQ0JBS2dBd0lCQWdJUUNnUncwSmE4aWhMSWtLYmZnbTdzU3pBTkJna3Foa2lHOXcwQkFRc0ZBREJoDQpNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ2hNTVJHbG5hVU5sY25RZ1NXNWpNUmt3RndZRFZRUUxFeEIzDQpkM2N1WkdsbmFXTmxjblF1WTI5dE1TQXdIZ1lEVlFRREV4ZEVhV2RwUTJWeWRDQkhiRzlpWVd3Z1VtOXZkQ0JEDQpRVEFlRncweE9UQTJNakF4TWpJM05UaGFGdzB5T1RBMk1qQXhNakkzTlRoYU1GOHhDekFKQmdOVkJBWVRBbFZUDQpNUlV3RXdZRFZRUUtFd3hFYVdkcFEyVnlkQ0JKYm1NeEdUQVhCZ05WQkFzVEVIZDNkeTVrYVdkcFkyVnlkQzVqDQpiMjB4SGpBY0JnTlZCQU1URlVkbGIxUnlkWE4wSUVOT0lGSlRRU0JEUVNCSE1UQ0NBU0l3RFFZSktvWklodmNODQpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEZKK2oxS2VaVkc0anpnUW9iMjNsUThQSlVOaFkzMXVmWmlodVV4DQpoWWM2SFNVNEx3MGZ4ZkE0M2E5RHBKbDc0TTNFNkYxWlJCT2ZKK2RXbmFpeVlEMFB4UklRZDR3SmlzdGk0VWFkDQp2ejYxSVlZL29RL0VseGsvWDdHRkRxdVl1eENTeUJkSHRUVk1YQ3hGU3ZRMkMvN2pXWkZEZkdHS0tOb1FTaUp5DQp3RGU4aWlIYlVPYWtMTW1YbU9UWnlXSm5GZFIvVEg1WU5UaU1LQ05VUEhBbGVHNElpZ0d4RHlML2did3JkRE5pDQpiREE0bFVOaEQweE52UGpROEJOS3FtNUhXRHZpclV1SGRDKzRocGkwR0pPMzRPM2lpUlYxNlltV1R1VkZOYm9VDQpMRFowK1BRdGN0Sm5hdHB1WktQR3lLWDZqQ3BQdnp6UHcvRWhORGxwRWRyWUhaTUNBd0VBQWFPQ0FjNHdnZ0hLDQpNQjBHQTFVZERnUVdCQlNSbjE0eEZhNFFuNjFnd2ZmQnpLcElOQzhNSmpBZkJnTlZIU01FR0RBV2dCUUQzbEExDQpWdEZNdTJid28rSWJHOE9Yc2ozUlZUQU9CZ05WSFE4QkFmOEVCQU1DQVlZd0hRWURWUjBsQkJZd0ZBWUlLd1lCDQpCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d01RWUlLd1lCQlFVSEFRRUVKVEFqDQpNQ0VHQ0NzR0FRVUZCekFCaGhWb2RIUndPaTh2YjJOemNDNWtZMjlqYzNBdVkyNHdSQVlEVlIwZkJEMHdPekE1DQpvRGVnTllZemFIUjBjRG92TDJOeWJDNWthV2RwWTJWeWRDMWpiaTVqYjIwdlJHbG5hVU5sY25SSGJHOWlZV3hTDQpiMjkwUTBFdVkzSnNNSUhPQmdOVkhTQUVnY1l3Z2NNd2djQUdCRlVkSUFBd2diY3dLQVlJS3dZQkJRVUhBZ0VXDQpIR2gwZEhCek9pOHZkM2QzTG1ScFoybGpaWEowTG1OdmJTOURVRk13Z1lvR0NDc0dBUVVGQndJQ01INE1mRUZ1DQplU0IxYzJVZ2IyWWdkR2hwY3lCRFpYSjBhV1pwWTJGMFpTQmpiMjV6ZEdsMGRYUmxjeUJoWTJObGNIUmhibU5sDQpJRzltSUhSb1pTQlNaV3g1YVc1bklGQmhjblI1SUVGbmNtVmxiV1Z1ZENCc2IyTmhkR1ZrSUdGMElHaDBkSEJ6DQpPaTh2ZDNkM0xtUnBaMmxqWlhKMExtTnZiUzl5Y0dFdGRXRXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQmZnDQplWHJ4SXJ0bGl4QnYrS01EZXFLeHROSmJaaUxEekpCa0dDZDRISTYzWDVlUzZCRWxKQm42bUk5ZVlWcnI3cU9MDQpUcDdXaU8wMlNmMVlycGF6L2VQU2paNjg0bzg5VUFHcHhPZmJnVlNNdm8vYTA3bi8yMjBqVVdMeHphSmhRTkx1DQpsQUNYd3dXc3hZZjh0d1A4Z2xrb0lIblVVTlRsaHN5eWwxWnp2VkM0YkRwSTRoQzZRa0pHeW5jMU1OcVlTTWo4DQp0WmJoUU53M0hkU21jVE8wTmMvSi9wSzJWWmM2ZkZiS0Jnc3BtemRIYzZqTUtHMnQ0bGlzWEV5c1Mzd1BjZzBhDQpOZnIxT2RsNStteWgzTW5NSzA4ZjZwVFh2ZHVMeitRWmlJaDhJWUwrWjZRV2dUWjllMmpuVjhqdXVtWDFJOEdlDQo3Y1pkdE5uVENCOGhGZndHTFVBPQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW9nSUJBQUtDQVFFQXdnbkdDOEMyOVZjRzI5eVYzVW5nKzV1VnRPcUMwanV1SEFIWFNGdkRwQVQxanlKdw0KSHZGTTV0RG5PM2ZOUmxkRUE2ZkZPckZDOHJSQSttdVN2VGJocE1tOWtDTUg0OHJQby9hMVFNY0J6Yk5uNmVJQQ0Kdm0vcUNQZS9LbG5nUlVIK3d5OC9yODBTSE1kUFl2bHltd1Q1NkNNTEMrQnZjWGJKT1EvcldPTzVjNkxob2lvLw0KVXRHUTVQMzhjSEtVTDBnZTdKK3U1TExPTHNrc0pLTEl0WXVGOTBqNk1EOWhXd1lPL0hhR0c3R08xTnNmaHBndw0KU2ZTYjRGSEh5ZENaT1lCcVMvOXVSd1oxbUlsM0RObExmTVBqZW1nWWkzcWhvVGRTcmQ2QmdRbFdYeFhMQnFpUQ0KTStQMHNDcUcreGpZWXRzR2pacFNTbjBMaHpHekZoQitRMUdOQ3dJREFRQUJBb0lCQUE5NXpoVGo0dlBBWkNpbQ0KK0VEMUFuK3UwZ3JpNVZvMUxsYkhnczhmbW9QN2JVWmtQY01LQmRNbStEcFMvTWxPYm50SUp6L2VJWFBRRXBxbQ0KZDhhbG1PdVd0NHJHY0h1bmtsWUdlRUJaWHZoMEJhYXV3dFp0Z0tJRWVIZTlRVmprd1pmNXJiK3N3SFFSSlhERQ0KYW5LWXZBSGF3YWZKMTdtWitzU1ZVM1Q4Zks4UE8vYzZtV2twUGJQMllqOGtPMFF4OFZNSXgwemxncHBtdEZHeg0KQVdVTjdUUXVOd3V5aGlZa2RPU0ZJNGVUM1VxVXF4aThkUnE2d2NQMDFDeDJnVTRkdklidm9RbVYvVCtRcG9HMA0KTTFRSjJWaXlOK2pWZysvem9VSjdzQmpWRmFWRXp3dUxjRUl5V0cvc1k1cCtSR05YcUhYaDBFQVNZQlJ3RGFZZQ0KS2RxcTVNRUNnWUVBOHJyb0pyeGtFN2gvM3ZyclhWTHlubTdTQ2xpM0ZiYTgwd0tEeXl4Skd0YWUxdmljQ3MxRw0KcUpkSmdaNEI0SjFKTk1id2pIdUFwYmtzOEdlL1UranI3MGNYdnlMVnFrUllLdGc5MWJVOURad2IxQ3M0SVlrbw0Kcy8vMnhFcXJLeWNweTBwc20xOVZQbnpFUTF0Q3FuQ0ppNEdadGJuZzRGb2VZN0ZlVVcwdmxDc0NnWUVBektWbg0KK1BYbVhwbytvWjd3V01mTmVBVUZ0RlZKTFVnN2JhSjQ5SjZZOG41SmZ2UmRqZDFPQklxWG93cXJrcXVsYk9pRg0KNXlQVFpIWkN3blN4dXFISDdGM2pPb1NUTWpPSHZOV0NZZTZtZEpNSzJwV1RCMlNnNXZhS052RkF6dnA3cmppYw0KV2dpWEFiV1dZZGsrVHl2MkdhZTc4S25BMkRnV3IyMkZYUENMR3FFQ2dZQWdMWWI1RzZCb3ZOeTJ3cXpSQWw0SA0KZ3NsMWRhMVB3NW5rbjBDNWZuVnlpV0VsUG0veFBxVlBWRDc2WCtmL3p0b1ZsUW51bGJESVIzUWRxcU5Dakc0Ng0KbWtJYnBKS09yK0RBVFVwbE9sR05yRlJFSERha3Uzb1o0cVRrQU1JUVJuRFQ4bG5UZngvZDJNeHI0WDFFK3daQQ0KNkQxb1NldjEwZnlWV3I0V0xWTlJZUUtCZ0doR3VDNEJqbnNSK1d2OVF0YmFLSFpKaU5pVXhJN1FTWWZaeSt4Sg0KakFHMEc5c1d4VHp1VVR5N0tmMG9DTGpad1pjMi9GUUV5MGhiZ2pUM3BVQkdBMHNMcENkRE9vWFFBQkJXY3ZOWA0KMlhWNUg0UzF4bzl6MVJFYSt0NTRHOS9iZm40TjFvMkI1d0ExK1FTdTM3TVQ0WGk5SVdURityK3lCTTBxNzFPbQ0KTmh0QkFvR0FaU2tOU0JEa3IxSzdrZzRTc2hZVEUrK3hrTVJ6SytnV3BHamdTK3M3VndVREd5eGlVbDRnWFN3ZQ0KZGFJZHhNT0U4MlhUOG9EYzlhMC9Zd1JwOVA4dkZSUTFzeEY1ZUo2U0h0TnRBd2VZZ1ZNTThuSktTSHV2QlZ4OQ0KMEk4b2t0UERHYURpQ2QySWZrQzN5aThZN3NpMllzNEFXNHFnNll3OEJ4bDQ1WkhIZE9FPQ0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0=
kind: Secret
metadata:
  name: tls-secret
  namespace: ns-v7g9
type: kubernetes.io/tls
---
apiVersion: v1
data:
  jdy.com.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlHcURDQ0JaQ2dBd0lCQWdJUUJ1ekhsZGUzdHI0MytYd1R6Tk0wcFRBTkJna3Foa2lHOXcwQkFRc0ZBREJlDQpNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ2hNTVJHbG5hVU5sY25RZ1NXNWpNUmt3RndZRFZRUUxFeEIzDQpkM2N1WkdsbmFXTmxjblF1WTI5dE1SMHdHd1lEVlFRREV4UkhaVzlVY25WemRDQlNVMEVnUTBFZ01qQXhPREFlDQpGdzB4T0RBNE1ERXdNREF3TURCYUZ3MHlNREEzTVRZeE1qQXdNREJhTUlHWU1Rc3dDUVlEVlFRR0V3SkRUakVTDQpNQkFHQTFVRUNBd0o1Ym0vNUxpYzU1eUJNUkl3RUFZRFZRUUhEQW5tdDdIbG5MUGx1SUl4T1RBM0JnTlZCQW9NDQpNT2Ezc2VXY3MrVzRndW1Ia2VpZHR1ZXl2dWFXbCtTNmtlZTlrZWU3bk9lbmtlYUtnT2FjaWVtWmtPV0ZyT1dQDQp1REVTTUJBR0ExVUVDd3dKNW9xQTVweXY2WU9vTVJJd0VBWURWUVFEREFrcUxtcGtlUzVqYjIwd2dnRWlNQTBHDQpDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFBOblpCYm9oMGdvcUI5aUtISUJRamNYcVNvdnpaDQpSTEF6WVVGTlJBV3dyeGhRMjBvcDhNZk5BVyt1U2FvaVphVENhQ3BwNjdTTGFST0NjMVFZN2RlMjBMQXQ4STVODQpCNDB3RDI1b0p3Y004aGg3ZVloejMvRFZXYnYzRXA5VVMrNzR4OHB5dGhKZ1JQeThDL0UvZnBneE9JRk52V1lJDQpYQlpkNW5oN2l2NFhuakE0NzdkRUx4SyttcHlhQ2tXQ1BtNit4Zk0xQktVdTNodlorRUxrWVVsN2VTQ3g4MDBvDQo4enBjSkplNm91eXFXbllRWWF0eExOeTg3UUJwZ3NrZHlnKzBQRkg2MjQyRjlQQVJKcE9veFN4ZHM4dk9ZUlFPDQoyZUdwTUlYZ0VpbzZUK0pQTU9oNVA4M1F4Q210SEZKcnYxQ2NxN1RZM0RyYXlINzFXQXR0dzgzUkFnTUJBQUdqDQpnZ01sTUlJRElUQWZCZ05WSFNNRUdEQVdnQlNRV1Ard25IV29VVlIzc2UzeW8wTVdPSjVzeFRBZEJnTlZIUTRFDQpGZ1FVaE82UTZSYnZIRVBjelJ0Yjg1UkhBZE50YmVFd0hRWURWUjBSQkJZd0ZJSUpLaTVxWkhrdVkyOXRnZ2RxDQpaSGt1WTI5dE1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCDQpCUVVIQXdJd1B3WURWUjBmQkRnd05qQTBvREtnTUlZdWFIUjBjRG92TDJOa2NERXVaR2xuYVdObGNuUXVZMjl0DQpMMGRsYjFSeWRYTjBVbE5CUTBFeU1ERTRMbU55YkRCTUJnTlZIU0FFUlRCRE1EY0dDV0NHU0FHRy9Xd0JBVEFxDQpNQ2dHQ0NzR0FRVUZCd0lCRmh4b2RIUndjem92TDNkM2R5NWthV2RwWTJWeWRDNWpiMjB2UTFCVE1BZ0dCbWVCDQpEQUVDQWpCMEJnZ3JCZ0VGQlFjQkFRUm9NR1l3SlFZSUt3WUJCUVVITUFHR0dXaDBkSEE2THk5dlkzTndNUzVrDQphV2RwWTJWeWRDNWpiMjB3UFFZSUt3WUJCUVVITUFLR01XaDBkSEE2THk5allXTmxjblJ6TG1kbGIzUnlkWE4wDQpMbU52YlM5SFpXOVVjblZ6ZEZKVFFVTkJNakF4T0M1amNuUXdDUVlEVlIwVEJBSXdBRENDQVg4R0Npc0dBUVFCDQoxbmtDQkFJRWdnRnZCSUlCYXdGcEFIWUFwTGtKa0xRWVdCU0h1eE9pekdkd0NqdzFtQVQ1RzkrNDQzZk5Ec2dODQozQkFBQUFGazg0amZxd0FBQkFNQVJ6QkZBaUVBMzIrQTFYaFg0MlVsSW8wVnIyNWl0UXpzY2R3MjRzUEp1UjhjDQphekhJa1NNQ0lGc3pGMmdBYnJhNEJJWTdyOTBJT1hxWEZlanVKSTBUY0g0TjBpMG5TUi9DQUhZQWgzVy81MWw4DQorSXhEbVYrOTgyNy9WbzFIVmpiL1NyVmd3YlRxLzE2Z2d3OEFBQUZrODRqZ2hRQUFCQU1BUnpCRkFpRUExOUEzDQpyYzQrSTF4bjFibis4UWRGQ0VGc3NsNVk5MXJ1blNDN0M4aGt1SndDSUNDY3Uzb3Zmb1c5VHBmVkdReVRxWmtJDQpnT2VZWkZLUlpESlhBcG5VRHdHREFIY0E3a3U5dDNYT1lMcmhRbWtmcStHZVpxTVBmbCt3Y3RpREFNUjdpWHFvDQovY3NBQUFGazg0amY5d0FBQkFNQVNEQkdBaUVBeWc2VkY1U1Rrak1qOEs2SXJyLzhOSmhmTmhmbDBGblJwaFhFDQpXbG9XK1lNQ0lRQ2VYWHl2U01KWitOV2pmZWRkV2ZyUkN5R2dwM2MxR3BXT1F1WkIzUXA1RERBTkJna3Foa2lHDQo5dzBCQVFzRkFBT0NBUUVBRXlhQ3o3RlV1eHBXZmJ6aDM1RGYyaXNMSjliazlIdmN5cEhvSkFzNWl5dmRkNkhRDQppa0V3QUR3VGk2dmFZejFLUHg4UXpLMm1ieFFVejIrcFhIZ1NJcDFVdmdCNC9jMnhoak1mVDZYSG8xRW9pNnNSDQpXck0zZG0weHhaMm84dnUyOFVkVk9XTnJ3SkliSkZEOCsyWk9QcTNpNzdQMTl0VHd3djc0YXQyRWxxSElOTko4DQo3OXVWOXdyU0EwNmZxSGs1QXNsN0FxZVZ5ZmZaOWdnR1Uyblc4ME1HRitxMjdvUmFvS1Rqc1FiWGtTZDdUWVpLDQp0QkYrWHQ0SDZaTUw3Um5CM3JNb01sai8ydkhqWFBVNmVaa3Bxclo1TTYwdEFEcW9vNFh0eG52QWRjTnVEQi9jDQowNGVzT0NJczhzMCtGaEtZU21rT01JUHN6dEdCK3ZXcmI5SG5mQT09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0NCk1JSUVpekNDQTNPZ0F3SUJBZ0lRQlViK0dDUDM0WlFkbzUvT0ZNUmhjekFOQmdrcWhraUc5dzBCQVFzRkFEQmgNCk1Rc3dDUVlEVlFRR0V3SlZVekVWTUJNR0ExVUVDaE1NUkdsbmFVTmxjblFnU1c1ak1Sa3dGd1lEVlFRTEV4QjMNCmQzY3VaR2xuYVdObGNuUXVZMjl0TVNBd0hnWURWUVFERXhkRWFXZHBRMlZ5ZENCSGJHOWlZV3dnVW05dmRDQkQNClFUQWVGdzB4TnpFeE1EWXhNakl6TkRWYUZ3MHlOekV4TURZeE1qSXpORFZhTUY0eEN6QUpCZ05WQkFZVEFsVlQNCk1SVXdFd1lEVlFRS0V3eEVhV2RwUTJWeWRDQkpibU14R1RBWEJnTlZCQXNURUhkM2R5NWthV2RwWTJWeWRDNWoNCmIyMHhIVEFiQmdOVkJBTVRGRWRsYjFSeWRYTjBJRkpUUVNCRFFTQXlNREU0TUlJQklqQU5CZ2txaGtpRzl3MEINCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXY0clJZMDNoR09xSFhlZ1dQSTkvdHI2SEZ6ZWtEUGd4UDU5RlZFQWgNCjE1MEhtOG9ESTBxOW0rMkZBbU0vbjRXNTdDanY4b1lpMi9oTlZFSEZ0RUovenpNWEFRNkNrRkxUeHpTa3dhRUINCjJqS2dRSzBmV2VRei9LRERscXhvYk5Qb21YT01KaEIzeTdjL09UTG8wbGtvN2dlRzRnazdoZmlxYWZhcGE1OVkNCnJYTElXNGRtcmdqZ2RQc3RVME5pZ3oyUGhVd1JsOXdlL0ZBd3VJTUlNbDVjWE1UaGRTQks2NlhXZFMzY0xYMTgNCjRORCtmSFdoVGtBQ2hKclpEVm91b0t6ek5Zb3E2dFphV215T0xLdjIzdjE0UnlaNWVxb2k2cW5tY1JJRDAvaTYNClU5SjVuTDFrclBZYlk3dE5qemdDK1BCWFhjV3FKVm9NWGNVdy9pQlRHV3pwd3dJREFRQUJvNElCUURDQ0FUd3cNCkhRWURWUjBPQkJZRUZKQlkvN0NjZGFoUlZIZXg3ZktqUXhZNG5tekZNQjhHQTFVZEl3UVlNQmFBRkFQZVVEVlcNCjBVeTdadkNqNGhzYnc1ZXlQZEZWTUE0R0ExVWREd0VCL3dRRUF3SUJoakFkQmdOVkhTVUVGakFVQmdnckJnRUYNCkJRY0RBUVlJS3dZQkJRVUhBd0l3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQURBMEJnZ3JCZ0VGQlFjQkFRUW8NCk1DWXdKQVlJS3dZQkJRVUhNQUdHR0doMGRIQTZMeTl2WTNOd0xtUnBaMmxqWlhKMExtTnZiVEJDQmdOVkhSOEUNCk96QTVNRGVnTmFBemhqRm9kSFJ3T2k4dlkzSnNNeTVrYVdkcFkyVnlkQzVqYjIwdlJHbG5hVU5sY25SSGJHOWkNCllXeFNiMjkwUTBFdVkzSnNNRDBHQTFVZElBUTJNRFF3TWdZRVZSMGdBREFxTUNnR0NDc0dBUVVGQndJQkZoeG8NCmRIUndjem92TDNkM2R5NWthV2RwWTJWeWRDNWpiMjB2UTFCVE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXcNCjhZZFZQWVFJL0M1ZWFycDgwczNWTE9PK0F0cGRpWGZ0OU9sV3dKTHdLbFV0UmZjY0tqOFFXL1BwNGI3aDZRQWwNCnVmZWp3UU1iNDU1T2pwSWJDWlZTK2F3WS9SOHBBWXNYQ25NMDlHY1NWZTRpdk1zd3lvQ1pQL3ZQRW4vTFBSaEgNCmhkZ1VQazhNbEQ5NzlSR29VV3o3cUdBd3FKQ2hpMjh1UmRzM3RoeCt2UlpaSWJFeVo2Mk5vMHRKUHpzU0dTejgNCm5RLy9qUDhCSXdyekJBVUg1V2NCQWJtdmdXZnJLY3V2K1B5R1BxUmNjNFQ1NVRsenJCbnpBelozb0NsbzlmVHYNCk85UHVpSE1LckM2VjZtZ2kwczJzYS9nYlhsUENEOVoyNFhVTXhKRWx3SVZURHVLQjBRNFlNTWxucE4vUUNoSjQNCkIwQUZzUStEVTBOQ08rZjc4WGY3DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  jdy.com.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRXBRSUJBQUtDQVFFQXp6WjJRVzZJZElLS2dmWWloeUFVSTNGNmtxTDgyVVN3TTJGQlRVUUZzSzhZVU50Sw0KS2ZESHpRRnZya21xSW1Xa3dtZ3FhZXUwaTJrVGduTlVHTzNYdHRDd0xmQ09UUWVOTUE5dWFDY0hEUElZZTNtSQ0KYzkvdzFWbTc5eEtmVkV2dStNZktjcllTWUVUOHZBdnhQMzZZTVRpQlRiMW1DRndXWGVaNGU0citGNTR3T08rMw0KUkM4U3ZwcWNtZ3BGZ2o1dXZzWHpOUVNsTHQ0YjJmaEM1R0ZKZTNrZ3NmTk5LUE02WENTWHVxTHNxbHAyRUdHcg0KY1N6Y3ZPMEFhWUxKSGNvUHREeFIrdHVOaGZUd0VTYVRxTVVzWGJQTHptRVVEdG5ocVRDRjRCSXFPay9pVHpEbw0KZVQvTjBNUXByUnhTYTc5UW5LdTAyTnc2MnNoKzlWZ0xiY1BOMFFJREFRQUJBb0lCQUdaSnRMdWRGRWdyYnJNeg0KN1J4MkZlcmZLRW85b2dLZzJUZ3IwTUFURFpvSC9VRmcxdTM0T2JFMS9jcnorMFBxbUJnTnNxNUIyQWlmc0sxTA0KUUI3a1BnRzFaOXJ0cmxsUkduMjRpR0JxcjV6UTM0d0lWUGNhZTNqZVNKN3hOdXkyWlR1eTZIbVM3bVJPZWRKYw0KTk5XS3FSZFhGT0ZxMXZUV2ZJWVM4TFBQeTVtZExVUXAwcGI5RnFsVHJGejlaTUVYYVB3WWFvUnNTUlU0aDRvNQ0KcXVkTzN6QVpRblFPR21OcWlwV0R3UmpSTjIvWTcrYlZGUWhhNHhoREk5MjlocG1yc0hBT0tZdUpIQ25YalJOOQ0Kc05YYmQ2SUxhRjI1QVpvVDBzenJNVjdyOHRJb3J3dE95bnlmTmVXejlmVktDVWZ3Y05EZ0MxTGFscUl3OTd4Rw0KU25XUTBVOENnWUVBL0tqVitiZDFNTmp4MnZxQkF5eFNOOVpiUTJvamJ5Ym8rTThxdkxCQy9kditjUWZHem10dA0KYk1ja2FQeVg5dUU5WEtXV0hSZjE0VnFoVWZTNjhCMk5oaDd0eXFPNkk1UXZjcGVsSkFVRWI2SmZLd0dUQ1d3Wg0KTVNXMHdlaFoyZmJiOFdUNEpGNHFrd0VCQ3IzS2NwWUFVM0FWNy9hM1RtRmdFNEw4SzZBSWg2Y0NnWUVBMGZQTg0KL1k5akwzNVIxR1JINzBtNU1McEwwQnRaY2tEbk5USmQySTRobzRLRGlsOHlhaDFlMHI2d0p4d1FSSXhGWC9qVg0KeGR6NjVQY01QTUlPZzBIWGJtQkp6OHA3Y29HNmU5TU5Sd1I1M0I5elU5ODZQZy9zRU9haWFCK2prVVhGZWRDeg0KREdtSkhOaHRtbGhpd3FQTUJBMVZXK2EvRXhlQnA3VDBoUWVtTGNjQ2dZRUF6RngvM3FFT1VEbFp2c1phTGNmZQ0KcEwxa1NpNENoVGhTdmxWSyt4NFN3YVQ4dEU0Vzl3V2JsNTJvREtjcS80eUdCbmNFNlhsazd5ZFFUcXNGdll3Wg0KMmI4UWxaUkN6ZDVoVm0za0xETkd1RWo4Y3h1dDQ3UWsyRVRvWk9OY01kbmpZdWhKY1prZEZKUitWRUxaQ2ovYg0KK2FFeWpVcmdUNnloZW9hN0UwbzVQQWNDZ1lFQXphM0YwREJIWDhDbFU2Z0dITEtobk0zMDlXUEZwYnRWaGZUWQ0Kb1F6a2dYV2JmZFF5NUdmdmZBL1pMQWMvSEpnNllvRzRrd1VnT1d5WWJYRkNuRzNGS2Rsa2xnN3NEc3B1TVY0Wg0KOU1lNnhkMTlzdDNPQmZ5OUsvVjFod0h2MEtLRWlnamRUenlZV1V6aFdzSlp4Z3FIRkRVbnVVZDlTcXZObGNrZA0KZnJGMnFBTUNnWUVBdkl3bFFWeWtDVlhnZEdOczB2QkZPK2pRQmJqNG1wZGZhcFFDckZ6UHZzaldUS21GOWRkLw0Kc2lGb2c5NVJJS25RYzkxd1NPQ1VTTWN5NEdYZkIxaEt0NjBUc3NXbnQxUmtGNGJPU293V2pDaHU4YzFCWVBEQQ0KenhDbzF4ZTVuVldQMmJZUGt1c2JOS2s4V1dPWTV0T3ZBRzBwQnFUOUxzc3lmdit0QlFHc0IyQT0NCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
kind: Secret
metadata:
  name: jdy-tls-secret
  namespace: ns-v7g9
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xOTAuMi4xNzEiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiZDhiZWM0MDI1MjBjNWJkMyIsImVtYWlsIjoidG9tX3Rhbmd3dSIsImF1dGgiOiJZV1J0YVc0NlpEaGlaV00wTURJMU1qQmpOV0prTXc9PSJ9fX0=
kind: Secret
metadata:
  name: regsecret
  namespace: ns-v7g9
type: kubernetes.io/dockerconfigjson
