apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: ns-ding1
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: ns-ding1
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: ns-ding1
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: ns-ding1
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      serviceAccountName: sa-ding1
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: zk
        imagePullPolicy: IfNotPresent
        image: 10.7.203.255/base/zookeeper:3.4.10
        resources:
          limits:
            cpu: 3
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper           --servers=3           --data_dir=/var/lib/zookeeper/data           --data_log_dir=/var/lib/zookeeper/data/log           --conf_dir=/opt/zookeeper/conf           --client_port=2181           --election_port=3888           --server_port=2888           --tick_time=2000           --init_limit=10           --sync_limit=5           --heap=512M           --max_client_cnxns=100           --snap_retain_count=3           --purge_interval=12           --max_session_timeout=60000           --min_session_timeout=5000           --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
      storageClassName: ding1-midware-nas
