apiVersion: v1
data:
  alertmanager.yaml:  Imdsb2JhbCI6IAogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiJyZWNlaXZlcnMiOiAKLSAibmFtZSI6ICJ3ZWIuaG9vayIKICAid2ViaG9va19jb25maWdzIjoKICAtICJ1cmwiOiAiaHR0cDovLzEwLjI0NC4zLjYzOjUwNTAveXpqIiAKICAtICJ1cmwiOiAiaHR0cDovLzEwLjI0NC4zLjYzOjgwNjAvZGluZ3RhbGsvamR5L3NlbmQiIAoicm91dGUiOiAKICAiZ3JvdXBfYnkiOiAKICAtICJqb2IiCiAgImdyb3VwX2ludGVydmFsIjogIjVtIgogICJncm91cF93YWl0IjogIjMwcyIKICAicmVjZWl2ZXIiOiAid2ViLmhvb2siCiAgInJlcGVhdF9pbnRlcnZhbCI6ICIxMmgiCiAgInJvdXRlcyI6IAogIC0gIm1hdGNoIjogCiAgICAgICJhbGVydG5hbWUiOiAiV2F0Y2hkb2ciCiAgICAicmVjZWl2ZXIiOiAid2ViLmhvb2siCg==
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
