apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    com.kingdee.kcs.clusterenv: ""
#    com.kingdee.kcs.deploytime: "1585038083"
#    deployment.kubernetes.io/revision: "1"
#  creationTimestamp: "2020-03-24T08:21:23Z"
#  generation: 1
  labels:
   # cluster: ns-v7yqy
    app: mservice
 #   sname: mservice
  name: mservice
  namespace: ns-v7yqy
#  resourceVersion: "139265"
#  selfLink: /apis/extensions/v1beta1/namespaces/clustername/deployments/mservice
#  uid: 72d5a725-6da8-11ea-ab79-08002792b40b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
#  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mservice
    #  cluster: clustername
  #    sname: mservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
  #    annotations:
  #      com.kingdee.kcs.zid: "5"
#      creationTimestamp: null
      labels:
        app: mservice
 #       cluster: clustername
   #     sname: mservice
    spec:
      serviceAccountName: sa-v7yqy
      containers:
      - env:
        - name: clusterName
          value: v7yqy001
        - name: configUrl
          value: 10.190.2.34:2181,10.190.2.37:2181,10.190.2.50:2181
        - name: appName
          value: mservice
        - name: configAppName
          value: mservice
        - name: WEB_PORT
          value: "8080"
        - name: ENABLE_JETTY
          value: "true"
        - name: appSplit
          value: "false"
        - name: APPSTORE_URL
          value: http://10.190.2.50:8090/appstore/cosmic
        - name: BIZLIBS
          value: bizweb.xml,hrmp.xml,bamp.xml,mmc.xml,data.xml,pmgt.xml,scmc.xml,tmc.xml,ssc.xml,drp.xml,scm.xml,hr.xml,fi-cal.xml,fi-calx.xml,fi.xml,taxc.xml,isc.xml,epm.xml,swc.xml,pccs.xml,ai.xml,macc.xml,ebg-aqap,3std-ebg
        - name: BOSLIBS
          value: bos.xml,bos-qing
        - name: TRDLIBS
          value: trd.xml
        - name: JVM_OPTS
          value: -server -Xms4096m -Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:NativeMemoryTracking=summary
            -Duser.timezone=GMT+8 -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
            -XX:HeapDumpPath=../logs/ -XX:+PrintGCApplicationStoppedTime
            -XX:+DisableExplicitGC -XX:+UseG1GC -XX:+PrintAdaptiveSizePolicy -XX:+PrintGCDetails
            -XX:+PrintGCDateStamps -Xloggc:../logs/gc.%t.log
        - name: webmserviceinone
          value: "true"
        image: kcr.kingdee.com/support/v2.0/mservice:v-20191220
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        name: mservice
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "3"
            memory: 8Gi
          requests:
            cpu: 1000m
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: v-015850380830
          readOnly: true
        - mountPath: /mservice/logs
          name: mservice-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
   #   schedulerName: default-scheduler
   #   securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: v-015850380830
      - name: mservice-data
        persistentVolumeClaim:
          claimName: cq-mservice-pvc
      nodeSelector:
        cq: v7yqy 
