apiVersion: v1
kind: ConfigMap
metadata:
  name: xlog-portal-conf
  namespace: ns-basesvc
  labels:
    name: xlog-portal-conf
data:
  application.yml: |
    database:
      type: postgresql
      url: jdbc:postgresql://pgm-bp1wqhoanej8w6lo146050.pg.rds.aliyuncs.com:1921/xlog?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&currentSchema=public
      username: monitor_user
      password: JIG2vjSpNF22Qp40
    server:
      port: 8080
      tomcat:
        uri-encoding: UTF-8
      servlet:
        context-path: /xlog
        jsp:
          init-parameters:
            development: true
    spring:
      profiles:
        include: core
      mvc:
        view:
          prefix: /WEB-INF/view/
          suffix: .jsp
        static-path-pattern: /**
        pathmatch:
          use-suffix-pattern: true # 支持 *.do 请求
    xlog:
      sessionOutTime: 21600000
      recordUrl: https://alerta-ali.jdy.com/alerts
      kafka:
        url: 10.190.2.191:9092,10.190.2.190:9092,10.190.2.192:9092
        groupId: xlog-portal
    shiro:
      enabled: true
      loginUrl: /login/login.do
      successUrl: /
      unauthorizedUrl: /?login
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xlog-portal
  namespace: ns-basesvc
  labels:
    k8s-app: xlog-portal
spec:
  selector:
    matchLabels:
      k8s-app: xlog-portal
  template:
    metadata:
      labels:
        k8s-app: xlog-portal
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      imagePullSecrets:
        - name: regsecret
      volumes:
        - name: xlog-portal
          configMap:
            name: xlog-portal-conf
            items:
              - key: application.yml
                path: path/to/application.yaml
      containers:
        - name: xlog-portal
          image: 10.190.2.171/xlog/xlog-portal:1.4.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: xlog-portal
              mountPath: /application.yml
              subPath: path/to/application.yaml
          env:
            - name: JAVA_OPTIONS
              value: "-Xms1024M -Xmx1024M"
          resources:
            limits:
              cpu: 2000m
              memory: 3Gi
            requests:
              cpu: 300m
              memory: 1000Mi
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xlog-portal
  namespace: ns-basesvc
  labels:
    k8s-app: xlog-portal
spec:
  selector:
    k8s-app: xlog-portal
  ports:
    - port: 8080
