apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: isc-v7g1-inde-pv
  name: isc-v7g1-inde-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  flexVolume:
    driver: alicloud/nas
    options:
      modeType: non-recursive
      path: /share/sqlserver/datafile
      server: 0003d141-j7e0.cn-hangzhou.extreme.nas.aliyuncs.com
      vers: "3"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
status:
  phase: Bound
